### ISSUE TITLE
[Text] lineHeight is not same as HTML element

### ISSUE THREAD

**Issue by sapics** [kangax/fabric.js#2059]
Please look at this jsfiddle.
http://jsfiddle.net/sapics/ftpbm2nn/

![line-height](https://cloud.githubusercontent.com/assets/11169954/6819361/458e04d4-d303-11e4-8292-18292043e35c.png)
(Black one is fabric.Text and red one is HTML element.)

When I set the same lineHeight for fabric.Text and HTML element, a result differs with one another.
I confirmed it on Chrome and IE11.

I wish to get same result between fabric.Text and HTML element.
Is it a expected result? Or, are there any tips to get the same result? Or, does it come from a bug?

**Comment by asturur** [comment]
fabric support overline and other text decoration and leave a little bit of space for them. more than html we took inspiration by tex editor. i ll put you a screenshot of current scheme so you get an idea.

**Comment by sapics** [comment]
@asturur Thank you very much for your answer!
I have not been able to understand [fabric.Text.proptype._fontSizeMult = 1.13], before your answer.
_fontSizeMult is for [a little bit of space for overline and other text decoration], isnt it?
I am looking forward to see your screenshot!

**Comment by asturur** [comment]
I forgot to include fontSizeMult that is that 1.12 ( or 1.13 param ).
When restiling itext, i just changed the default lineheight from 1.3  to 1.3 / 1.13

It would be natural thinking to divide internally by this fraction, but then using lineheight = 1 would bring to innatural results.

![image](https://cloud.githubusercontent.com/assets/1194048/6820510/4133f372-d2d0-11e4-8a3d-0fcda6f997e1.png)

**Comment by sapics** [comment]
@asturur
Thank you for your manuscript!
I understand about fontSizeMult is multiplicative factor for overline and decoration.
Therefore, lineHeight 1.3 to 1.3 / 1.13 makes same result.
Your description is exactly!
I can make the same result between fabric.Text and HTML element!
http://jsfiddle.net/sapics/ftpbm2nn/28/

Thus, my question about lineHeight is solved!
Thank you!


On the other hand, http://jsfiddle.net/sapics/ftpbm2nn/30/ ,
the position top and left have some differences between them.
About left +8, and top (+3 for fontSize:30px or +7 for fontSize:70px) apart from HTML element on Chrome browser.

![left-top](https://cloud.githubusercontent.com/assets/11169954/6822069/2daf5d6e-d320-11e4-979d-669516b42c7d.png)


Are there any tips to set same left-top position between fabric.Text and HTML element?
It looks very difficult to make same position. For my purpose, it would be enough that it is near by.
I'm sorry for an additional question.

**Comment by asturur** [comment]
Sorry i thought i answered.
Consider removing margin and padding to your html.

adding:

```
* {
  padding:0px;
  margin:0px;
}
```

Changes your situation for good.
Vertical align is not fixed, consider iText expands lineheight in the bottom, maybe html not.

**Comment by sapics** [comment]
Thank you very much for your advice!

It is my falut, I am sorry.
```css
* {
  margin:0;
  padding:0;
}
```
works well! Thank you!!

I set vertical-align of fabric.Text by setting
ctx.textBaseline = 'bottom' in fabric.js.
It looks far away from alphabetic-baseline.
http://jsfiddle.net/sapics/ftpbm2nn/40/

Is it my misunderstanding of your advice?

**Comment by sapics** [comment]
Thank you very much for your many helps!

I did my porpose.
http://jsfiddle.net/sapics/ftpbm2nn/53/

I will use
```javascript
 textBaseline = 'bottom'
 _fontSizeFraction = 0
```
for my purpose, because, the alphabetic baseline depends on font.
However, it will cause some problems when multi-font in one-line, because baseline place is not same.

It looks strange in text.class.js for consistency with HTML.
https://github.com/kangax/fabric.js/blob/master/src/shapes/text.class.js#L518
```javascript
  - | this._getTopOffset() + lineHeights + maxHeight,
  + | this._getTopOffset() + lineHeights + heightOfLine
          - 0.5 * (this.lineHeight - 1) * this.fontSize,
```
Of coarse, if it is expected result, it is not a problem.

**Comment by asturur** [comment]
There was some reason to use _fontSizeFraction = 0.25
I think it was SVG consistency, but i cannot figure out now.

We never pursued HTML consistency.

**Comment by sapics** [comment]
I feel _fontSizeFraction=0.25 is good for multi-style in one-line,
because baseline is always same position.
I understand, fabric.js is consistent with SVG.

My problem is solved! I close this issue.
Thank you very much for kindly teaching!

**Comment by arsen2010** [comment]
@sapics  thank you for help.

**Comment by sapics** [comment]
@asturur helped me a lot. Thank you @asturur for your kindness!
I am very happy, if this issue can any help to you!

**Comment by vijaygurjar** [comment]
Can we set line height in pixel instead of percentage in fabricjs. Please guide me to solve this

**Comment by codemilli** [comment]
@asturur Hello, I am currently updating from version 1.4.11 to version 4.5.1. I thought that line-height 1.3 of 1.4.11 version was the same as 1.13 from 4.5.1 version, is this correct?

Additionally, the text height is different between 1.4.11 version and 4.5.1 version even though the style is same, is there any hint about this? 
(Thank you so much 😄 )
