### ISSUE TITLE
Textbox - Cursor placement when aligned right or center

### ISSUE THREAD

**Issue by inssein** [kangax/fabric.js#2366]
I found another bug today, which I am surprised I found this late. The Textbox class has a _setLineWidths() function that gets called from _initDimensions(). However, the line widths it sets are very different from the ones that get calculated in _getLineWidth(). This effects the cursor placement when the text is aligned to the center, or to the right.

I will submit a PR that just removes setting _setLineWidths(), that way it can be lazily cached by getLineWidths().

@jafferhaider does that sound right?

**Comment by asturur** [comment]
let me check also.
i added that function for a purpose.

**Comment by inssein** [comment]
@asturur sounds good

**Comment by jafferhaider** [comment]
Yep, I was under the impression that this bug was fixed. It was introduced in some of the recent IText changes. It'd be awesome if @asturur could help out.

**Comment by asturur** [comment]
yes, i wrongly populated that array, for lazyness.
I should go around the code and check where this array is accessed directly and put the getWidthOfLine function instead.

Also _getCachedLineOffset is an overkill in my opinion, what it does is caching a function call with an if and a subtraction... The heavy job is in getLineWidth() that is already cached.

I will submit a pr if possible today.

**Comment by inssein** [comment]
thanks @asturur

**Comment by NealHumphrey** [comment]
@asturur - It looks like this is still an issue in 1.6.0-rc.1 - is that expected? It looks like the fix via #2368 was merged in to Master a long while back.
