### ISSUE TITLE
Pixelated edges of image after loadFromJson even after applying SlickHack resize filter

### ISSUE THREAD

**Issue by vxrai** [kangax/fabric.js#3190]
@kangax  To fix the pixelation of images on resize i used the sliceHack resize filter. After applying them, i resized the image to approx 1/3 of its original size and this time the image din’t pixelate. Everything worked perfect, life was awesome before I saved the canvas state using Canvas.toJson.
Now the next time when i reloaded the saved backup again on canvas using Canvas.loadFromJson the same resized image is now pixelated from it edges.
Not sure why the anti-alised state was not retained when the images reloaded on canvas using LoadFromJson

Original image - 
![image](https://cloud.githubusercontent.com/assets/7886890/17844971/24a99b08-685c-11e6-8c05-d0f981bfdc28.png)

Anti-aliasing worked perfect on resizing - 
![image](https://cloud.githubusercontent.com/assets/7886890/17844980/3857ca80-685c-11e6-9c7d-72b5faef29ea.png)

After resizing the image; the json of the canvas was saved in db using canvas.tojson

canvas.toJSON(['_controlsVisibility','transparentCorners','cornerSize','borderColor','cornerColor','cornerSize','borderOpacityWhenMoving'])

When canvas.LoadFromJson is applied to reload the small resized image back on canvas, the image results with pixelated edges -

![image](https://cloud.githubusercontent.com/assets/7886890/17845239/04b6909c-685e-11e6-9e8d-4b5fc98f8d42.png)

Please suggest what should be done to retain the smooth edges of the images after the image is reloaded using loadFromJson. 
Your help will be really appreciated!

**Comment by asturur** [comment]
can you provide a fiddle?

**Comment by vxrai** [comment]
@asturur  thanks for your quick response. 
I did setup fiddle for this, please check this link - http://jsfiddle.net/varun598/jagfhh8d/11/

But for some reason the code to implement sliceHack is causing issues on fiddle but working fine on localhost.

**Comment by vxrai** [comment]
@asturur did you get a chance to check the fiddle out?
http://jsfiddle.net/varun598/jagfhh8d/22/

**Comment by asturur** [comment]
i checked, is a defect.
I ll try to fix it.

**Comment by vxrai** [comment]
fingers crossed! good luck

**Comment by vxrai** [comment]
Hi @asturur , hows's it going? Any luck with this yet?

**Comment by asturur** [comment]
http://jsfiddle.net/jagfhh8d/29/

oh dear, you made me work on fabric 1.5.0
The bug does not exist anymore  in 1.6.3

**Comment by vxrai** [comment]
@asturur - I checked the fiddle that you shared -  http://jsfiddle.net/jagfhh8d/29/ and the issue still exist.
When i downscale the image on canvas1 (sliceHack is applied and edges are smooth) 

![screen shot 2016-08-26 at 2 21 01 pm](https://cloud.githubusercontent.com/assets/7886890/17999785/6bb529ce-6b98-11e6-9b1f-373f81ce2f52.png)


but when the json of downscaled image on canvas1  is loaded on canvas2, the image that renders on canvas2 is still not as smooth as on canvas1 

![screen shot 2016-08-26 at 2 23 32 pm](https://cloud.githubusercontent.com/assets/7886890/17999831/bb8a5ffa-6b98-11e6-810e-a20ec46ec74b.png)

but when you click on the image and resize in canvas2 slicehack does work but not right after the image loads on canvas2. The image that loads on canvas2 (ONLOAD) should be as good as it appears on canvas1.
What do you think about this? Please let me know incase there's any doubt or you want me to elaborate on any specific point.

**Comment by vxrai** [comment]
@asturur - on resize it does work fine, slicehack is applied, but right after the image loads from loadFromJson, its not smooth, you have to click on the image and resize it for smoothing the edges. But look a the image right after the image loads after loadFromJson

**Comment by vxrai** [comment]
@asturur my skype id is varun.raioffice Please share your skype id or add me so that I can explain more about this issue

**Comment by asturur** [comment]
there are 2 separate issue i perfectly know.
1) resize filters not applied after loading from json, present in 1.5 solved later.
2) loading callback after json does not wait for filter loading. now i fixing that in a pr.

**Comment by vxrai** [comment]
@asturur - okay so you mean that the case i'm referring to, in which after load from json, the image edges are pixelation, unless you select the image with mouse and resize. This one is a part of 2nd case you mentioned above which is yet to be fixed in the new release?

**Comment by asturur** [comment]
yes

**Comment by vxrai** [comment]
@asturur - i hope you are getting closer to fixing the issue. Please let me know once its fixed!

**Comment by asturur** [comment]
is fixed. i m checking tests and other stuff.

**Comment by vxrai** [comment]
@asturur  - Is the testing complete and finally fixed? If yes, then from where can i see the fix and get the latest code? Please share the link that i can merge in my current build. Where can I see the fix?

**Comment by asturur** [comment]
take current master and give a check

**Comment by vxrai** [comment]
@asturur - this is brilliant, the issue seems to be fixed now but after upgrading to the new version the sendBackward and sendForward functionality is working differently than from the older version of fabric i was using. 
So earlier when i selected an object on canvas, and on applying sendBackward, the index of the object changed and it moved backwards bringing the intersecting object forward WHILE THAT IMAGE WAS ALREADY IN ACTIVE STATE.
Now after upgrading to the newer version of fabricjs, when i select the image and apply sendBackward, the active object doesn't seem to move backward UNTIL ITS DEACTIVATED/UNSELECTED
Can you please help, how can i see the object move backward and the overlapping object move forward while the property is applied IN ACTIVE STATE

**Comment by vxrai** [comment]
in both cases the Object does move Backwards when i apply sendBackward functionality,  but the updated state is not visible unless the object is deselected on canvas. So how can i still see the updated state of object after applying sendBackward/sendForward property even if the object is iu in selected/active state

**Comment by vxrai** [comment]
@asturur the other way to put this issue is, that on active state the object always shows on front of other overlapping objects. How can i disable that, and show the object backwards even if its active.

**Comment by vxrai** [comment]
@asturur - If you look at the images below, the image of dress that is in center is behind the other two dresses on its sides, but when you select the dress in the center, in active state it shows on top of the other 2 dresses, which was not the case earlier in previous version of fabric. So how can i disable this feature. Secondly, when the dress is selected and i apply sendForward/sendBackward, the change is not visible realtime, unless is deselect the active object.
![screen shot 2016-09-06 at 9 32 37 pm](https://cloud.githubusercontent.com/assets/7886890/18281249/ce36c99c-7479-11e6-8bfd-6290aac0ab8a.png)
![screen shot 2016-09-06 at 9 32 50 pm](https://cloud.githubusercontent.com/assets/7886890/18281254/d2c09100-7479-11e6-9698-0eb826637a80.png)

**Comment by asturur** [comment]
preserveObjectsStacking has always been false as default and should be also now. no changes there.

**Comment by vxrai** [comment]
Got it bro. thanks a ton :)
