### ISSUE TITLE
Textbox Issue when deleting first word on IE11

### ISSUE THREAD

**Issue by ImTheMark** [kangax/fabric.js#4107]
## Version
1.7.11 (or higher)

## Test Case
https://jsfiddle.net/m8zfr5gk/
Use IE11 browser

## Steps to reproduce

1. Add Textbox to canvas
2. Ensure that textbox content has at least 2 words separated by a space, ex: "Test Text"
3. Edit text and put cursor after last letter of the first word and before the space character. "Test{cursor here} Text"
4. Use the backspace key and delete the first word.
5. Attempt to edit the text while cursor is still active.

## Expected Behavior
User is able to edit the text freely without any issues.

## Actual Behavior
User cannot edit the text, add or remove characters without deselecting the active text object.

**Comment by ImTheMark** [comment]
Same behavior applies on the current Kitchensink demo.

**Comment by asturur** [comment]
does the ie11 dev console complain about something?

**Comment by ImTheMark** [comment]
Hi @asturur, thanks for your reply.
I actually just saw that the console has error upon deleting the first word.

Here's the steps that I did.

1. Add textbox in canvas
2. Put cursor after the word Lorem and hit backspace until the end

![kitchensinkerror1](https://user-images.githubusercontent.com/5908868/28293451-1008628c-6b09-11e7-99cf-5388110a437d.PNG)

3. When the cursor hits the start of text, it triggers the following error
(NOTICE the rendered text, it's still showing the 'L' from Lorem even if it's not there anymore)
![kitchensinkerror2](https://user-images.githubusercontent.com/5908868/28293452-10196aa0-6b09-11e7-96bd-a0a29ccc6f43.PNG)

4. I deselect the text and the 'L' is gone
![kitchensinkerror3](https://user-images.githubusercontent.com/5908868/28293450-100764ae-6b09-11e7-8a33-1f770d09a1e8.PNG)

5. Here's the exact line of code where its failing
![kitchensinkerror4](https://user-images.githubusercontent.com/5908868/28293453-1024f672-6b09-11e7-8153-283b5407d64a.PNG)

**Comment by asturur** [comment]
very weird. i m replicating with a VM. won't be easy to figure out

**Comment by asturur** [comment]
The bug appear in 1.7.9 but not in 1.7.9

**Comment by asturur** [comment]
looks like is the wrap style property, that i just removed for other purposes and i swapped with wrap=off. Looks like is fixed in upcoming 1.7.17

**Comment by ImTheMark** [comment]
Hello @asturur, is there any way for me to fix this on the version that I am currently using (1.7.11)? Thank you for investigating the problem.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/28614535-77ea0af6-71f6-11e7-992a-eb01a916c1db.png)

this is the change that interests you. I would move the the 1.7.17 anyway. You should have just fixes and no problems

**Comment by ImTheMark** [comment]
Hello @asturur,
I tried to add line 13 and modified line 15 from your code snippet as shown below:

![image](https://user-images.githubusercontent.com/5908868/28641889-7108da82-7205-11e7-8b0e-ad0350d42162.png)

And I am still getting the same behavior. I cannot edit the text.

**Comment by asturur** [comment]
i ll try again on latest. i have win 10 ie11
